language: cpp
sudo: false
dist: trusty

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2269819ce0333700fe69
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

compiler:
- g++

before_install:
- wget https://github.com/01org/tbb/releases/download/2018_U2/tbb2018_20171205oss_lin.tgz
- tar xf tbb2018_20171205oss_lin.tgz
- export TBBROOT=`pwd`/tbb2018_20171205oss
- export TBB_ARCH_PLATFORM=intel64/gcc4.4
- export CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
- $CXX -v
- cmake --version
- mkdir ./build
- cd ./build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
- ctest -C Release
