language: cpp
sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2269819ce0333700fe69
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

compiler:
- g++

before_install:
- wget http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz --no-check-certificate
- tar xf cmake-3.3.2.tar.gz
- cd cmake-3.3.2
- ./bootstrap --system-curl --prefix=$HOME/usr
- make
- make install
- export PATH=$HOME/usr/bin:$PATH
- cd ..
- wget https://www.threadingbuildingblocks.org/sites/default/files/software_releases/linux/tbb44_20150728oss_lin_0.tgz
- tar xf tbb44_20150728oss_lin_0.tgz
- export TBBROOT=`pwd`/tbb44_20150728oss
- export TBB_ARCH_PLATFORM=intel64/gcc4.4
- export CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
- $CXX -v
- cmake --version
- mkdir ./build
- cd ./build
- cmake ..
- make
- ctest
