version: 0.0.1.{build}

#environment:

platform: x64
configuration: Release

clone_folder: c:\projects\perflib

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - architecture: Win64
      tbb_architecture: intel64
      vs_ver: 12 2013
    - architecture: Win64
      tbb_architecture: intel64
      vs_ver: 14 2015
    - architecture: #Win32
      tbb_architecture: ia32
      vs_ver: 12 2013
    - architecture: #Win32
      tbb_architecture: ia32
      vs_ver: 14 2015

build:
  project: c:\projects\perflib\build\perflib.sln

clone_depth: 5

matrix:
  fast_finish: true

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

before_build:
- echo ------------------------------- DOWNLOAD--------------------------------
- if not exist c:\projects\downloads ( mkdir c:\projects\downloads )
- cd c:\projects\downloads
- if not exist tbb44_20150728oss_win.zip (appveyor DownloadFile https://www.threadingbuildingblocks.org/sites/default/files/software_releases/windows/tbb44_20150728oss_win.zip -FileName tbb44_20150728oss_win.zip && 7z.exe x tbb44_20150728oss_win.zip -oc:\projects\deps > unzip_tbb.log)
- set TBBROOT=c:\projects\deps\tbb44_20150728oss
- cd c:\projects\perflib
- echo --------------------------------- CMAKE ---------------------------------
- cmake --version
- set TBB_ARCH_PLATFORM=%tbb_architecture%/vc12
- echo %TBB_ARCH_PLATFORM%
- mkdir c:\projects\perflib\build
- cd c:\projects\perflib\build
- set toolset="Visual Studio %vs_ver% %architecture%"
- cmake .. -G %toolset%


test_script:
- set "path=%PATH%;%TBBROOT%\bin\%TBB_ARCH_PLATFORM%"
- echo %PATH%
- msbuild c:\projects\perflib\build\RUN_TESTS.vcxproj

cache:
- c:\projects\downloads
