version: 0.0.1.{build}

#environment:

platform: x64
configuration: Release

clone_folder: c:\projects\perflib

init:
  - git config --global core.autocrlf input
  - mkdir c:\projects\downloads
  - appveyor DownloadFile https://www.threadingbuildingblocks.org/sites/default/files/software_releases/windows/tbb44_20150728oss_win.zip -FileName c:\projects\downloads\tbb44_20150728oss_win.zip
  - 7z.exe x c:\projects\downloads\tbb44_20150728oss_win.zip -oc:\projects\deps > unzip_tbb.log
  - dir c:\projects\deps
  - set TBBROOT=c:\projects\deps\tbb44_20150728oss

environment:
  matrix:
    - architecture: Win64
      tbb_architecture: intel64
    - architecture:
      tbb_architecture: ia32

build:
  project: c:\projects\perflib\build\perflib.sln

clone_depth: 5

matrix:
  fast_finish: true

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

before_build:
- cmake --version
- set TBB_ARCH_PLATFORM=$env:tbb_architecture/vc12
- mkdir c:\projects\perflib\build
- cd c:\projects\perflib\build
- cmake .. -G "Visual Studio 12 Win64"


test_script:
- msbuild RUN_TESTS.vcxproj
