version: 0.0.1.{build}

#environment:

platform: x64
configuration: Release

clone_folder: c:\projects\perflib

init:
  - git config --global core.autocrlf input
  - appveyor DownloadFile https://www.threadingbuildingblocks.org/sites/default/files/software_releases/windows/tbb44_20150728oss_win.zip
  - 7z.exe x tbb44_20150728oss_win.zip c:\projects\perflib\deps\tbb44_20150728oss_win
  - set TBBROOT=c:\projects\perflib\deps\tbb44_20150728oss_win
  - set TBB_ARCH_PLATFORM=intel64/vc12

build:
  project: perflib.sln

clone_depth: 5

matrix:
  fast_finish: true

skip_commits:
# Add [av skip] to commit messages
  message: /\[av skip\]/

before_build:
- cmake --version
- mkdir c:\projects\perflib\build
- cd c:\projects\perflib\build
- cmake .. -G "Visual Studio 12 Win64"

test_script:
- msbuild RUN_TESTS.vcxproj
